name: GitHub-Actions
on: 
  push:
    branches:
      - master
    paths-ignore:
      - .github/**
      - bin/**
      - .gitignore
      - .rspec
      - CHANGELOG.md
      - CODE_OF_CONDUCT.md
      - LICENSE.txt
      - README.md
  pull_request:

jobs:
  rspec:
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v2
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.6.6
        bundler-cache: true
    - name: Test with Rspec
      run: bundle exec rspec
  rubocop:
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v2
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.6.6
    - name: rubocop
      uses: reviewdog/action-rubocop@v1
      with:
        rubocop_version: gemfile
        github_token: ${{ secrets.github_token }}
        reporter: github-pr-review # Default is github-pr-check